[features]
seeds = false
skip-lint = false
[programs.localnet]
defi_go_fund_me = "4ihLbA5Q6je6Mf3QGAMDKMPsixZpmZHVjQupda2w9QZ5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
